version: "3.9"
services:
  analysis:
    build:
      context: ./analysis
    working_dir: /app/analysis
    volumes:
      - ./:/app
    environment:
      STREAMLIT_SERVER_ADDRESS: 0.0.0.0
      STREAMLIT_SERVER_PORT: 8514
    ports:
      - 127.0.0.1:8514:8514

  stats:
    build:
      context: ./stats
    working_dir: /app
    volumes:
      - ./stats:/app
      - ./data:/app/data
    environment:
      STREAMLIT_SERVER_ADDRESS: 0.0.0.0
      STREAMLIT_SERVER_PORT: 6608
      AIRTABLE_API_KEY:
    ports:
      - 127.0.0.1:6608:6608
