version: "3.9"
services:
  app:
    image: node:23.4.0-alpine3.20
    working_dir: /app
    command: npm run dev
    volumes:
      - ./:/app
    ports:
      - 127.0.0.1:6600:3000
      - 127.0.0.1:6601:24678
    environment:
      NUXT_HOST: 0.0.0.0
      AIRTABLE_API_KEY:
