on:
  workflow_dispatch:
  schedule:
    - cron: "*/10 * * * *"

jobs:
  fetch:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v2.1.2
        with:
          node-version: 16
      - run: npm install
      - run: node count.js >> data/counts.jsonl
      - uses: stefanzweifel/git-auto-commit-action@v4
