on:
  workflow_dispatch:
  #schedule:
  #  - cron: "*/10 * * * *"
jobs:
  fetch:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: >
          git config --global user.email "steffkes@firefighter-competitions.actions.github.site" &&
          git config --global user.name "steffkes" &&
          git subtree pull \
            --prefix data \
            https://github.com/steffkes/firefighter-competitions-data.git main --squash &&
          git push
