on:
  workflow_dispatch:

jobs:
  fetch:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: tmp/improve-data-collection
      - uses: actions/setup-node@v2.1.2
        with:
          node-version: 16
      - run: npm install
      - run: node count.js >> data/counts.jsonl
      - run: node participants.js
      - run: node teams.js
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          branch: tmp/improve-data-collection
          create_branch: true
