on:
  workflow_dispatch:

jobs:
  init:
    outputs:
      spiders: ${{ steps.generate-matrix.outputs.spiders}}
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./analysis
    steps:
      - uses: actions/checkout@v4
        with:
          ref: data-collection
      - name: generate matrix
        id: generate-matrix
        run: echo "spiders='${{ toJSON($(find spider/ -name "*rec*.py" | sort | jq -ncR '[inputs]')) }}'" >> "$GITHUB_OUTPUT"
  my_echo:
    runs-on: ubuntu-latest
    needs:
      - init
    steps:
      - name: Echo previous outputs
        run: echo "${{ toJSON(needs.init.outputs) }}"
  my_matrix:
    runs-on: ubuntu-latest
    needs:
      - init
    strategy:
      matrix:
        spider: ${{ fromJSON(needs.init.outputs.spiders) }}
    steps:
      - name: Matrix => (${{ matrix.spider }})
        run: |
          echo ${{ matrix.spider }}
