on:
  workflow_dispatch:
  #schedule:
  #  - cron: "*/10 * * * *"
jobs:
  fetch:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: >
          git subtree pull \
            --prefix data \
            https://github.com/steffkes/firefighter-competitions-data.git main --squash
      - uses: stefanzweifel/git-auto-commit-action@v4
