on:
  workflow_dispatch:

jobs:
  fetch:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    defaults:
      run:
        working-directory: ./analysis
    steps:
      - uses: actions/checkout@v4
        with:
          ref: data-collection
      - name: dev
        run: $(find spider/ -name "*rec*.py" | sort)
      - name: Set env
        run: echo "SPIDERS='$(find spider/ -name "*rec*.py" | sort)'" >> $GITHUB_ENV
      - name: Test
        run: echo $SPIDERS
