name: "deploy"
on:
  workflow_dispatch:
  schedule:
    - cron: "10 10 * * *"

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - name: REST API with curl
        run: curl "https://api.vercel.com/v1/integrations/deploy/prj_sU7qIoQrCyB4BduUKffIJcj1pQac/HLRF2yvyNy"
