name: "refresh webhook"
on:
  workflow_dispatch:
  schedule:
    - cron: "0 10 * * 2,4"

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - name: REST API with curl
        run: >
          curl
            -X POST
            -H "Authorization: Bearer ${{ secrets.AIRTABLE_API_KEY }}"
            "https://api.airtable.com/v0/bases/appF8BPHzWCy6OKVF/webhooks/achSlOmcXNPVqyFdl/refresh"
